image: node:alpine

variables:
  PUBLIC_URL: /react-master-group-1

cache:
  paths:
  - node_modules

stages:
- deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build 
    - rm -rf public
    - mv build public
  artifacts:
    paths:
    - public
  only:
    - develop
 
