image: node:alpine

variables:
  REACT_APP_API_URL: https://3w-bet-mangeur-api.lycee-stvincent.net:9000/

pages:
  cache:
    paths:
      - node_modules/
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
    - rm -rf react-master-group-1
  artifacts:
    paths:
    - public
  only:
    - develop
    - master

