image: node:alpine

variables:
  REACT_APP_API_URL: http://151.80.136.92:9000/

stages:
- deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build 
    - rm -rf public
    - mv build public
  artifacts:
    paths:
    - public
  only:
    - develop
 
